# Generated by Django 3.1.7 on 2021-08-31 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20210831_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.ImageField(upload_to='uploads/<function user_directory_path at 0x7f09ac64ec10>')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField(max_length=100, verbose_name='Company Name')),
                ('title', models.TextField(max_length=100, verbose_name='Title and Designation')),
                ('desc1', models.TextField(max_length=100, verbose_name='Work description 1')),
                ('desc2', models.TextField(max_length=100, verbose_name='Work description 2')),
                ('start_date_year', models.TextField(verbose_name='Start date year')),
                ('present_date_year', models.TextField(null=True, verbose_name='present date year')),
                ('start_date_month', models.TextField(verbose_name='Start date month')),
                ('present_date_month', models.TextField(null=True, verbose_name='present date month')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.TextField(verbose_name='Skill name')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('github', models.TextField(blank=True, null=True, verbose_name='GitHub URL')),
                ('gitlab', models.TextField(blank=True, null=True, verbose_name='GitLab URL')),
                ('linkedIn', models.TextField(blank=True, null=True, verbose_name='linkedIn URL')),
                ('portfolio', models.TextField(blank=True, null=True, verbose_name='Portfolio Link')),
                ('other', models.TextField(blank=True, null=True, verbose_name='Other URLs')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbies', models.CharField(choices=[('SI', 'Singing'), ('DA', 'Dancing'), ('PL', 'Playing'), ('SK', 'Sketching'), ('TR', 'Travelling'), ('RE', 'Reading')], default=None, max_length=2)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Educations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_year', models.IntegerField()),
                ('end_date_year', models.IntegerField()),
                ('uni_name', models.TextField(verbose_name='Name of Institute')),
                ('course', models.TextField(verbose_name='Course Name')),
                ('percentage', models.TextField(verbose_name='Percent or CGPA')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Certificate name')),
                ('date', models.DateField(null=True, verbose_name='Date of Issue')),
                ('certificate', models.ImageField(upload_to='uploads/<function user_directory_path at 0x7f09ac64ec10>/certificates')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
    ]
