# Generated by Django 3.1.7 on 2021-08-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='certificate',
            field=models.ImageField(upload_to='uploads/<function user_directory_path at 0x7f523a8a4c10>/certificates'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume',
            field=models.ImageField(null=True, upload_to='uploads/<function user_directory_path at 0x7f523a8a4c10>'),
        ),
    ]
